baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-toc

defaults:
  - scope:
      path: ""
    values:
      toc: true

exclude:
  - justfile
  - scripts/
  - boundaries/
  - mise.toml
