name: Update data from OSM

on:
  schedule:
    - cron:  "0 12 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Osmium CLI tool
        run: sudo apt install -y osmium-tool
      - name: Install DuckDB
        run: "curl https://install.duckdb.org | sh"
      - name: Install Python dependencies
        run: pip install osmium pyarrow shapely
      - name: Install just
        run: cargo install just
      - name: Build parks.parquet file
        run: just data
      - name: Upload parquet file to artifact storage
        uses: actions/upload-artifact@v4
        with:
          name: parks
          path: |
            parks.parquet
            parks.timestamp
